const express=require('express'),http=require('http'),fs=require('fs'),path=require('path');
const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server),ROOT=__dirname;
app.use(express.json()); app.use(express.static(path.join(ROOT,'public'))); app.use('/image',express.static(path.join(ROOT,'image')));
const cards=JSON.parse(fs.readFileSync(path.join(ROOT,'cards.json'),'utf8'));
app.get('/healthz',(q,r)=>r.status(200).send('ok'));
const byId=Object.fromEntries(cards.map(c=>[c.id,c]));
const dataDir=process.env.DATA_DIR||ROOT; fs.mkdirSync(dataDir,{recursive:true});
const profilePath=path.join(dataDir,'profiles.json'); let profiles={}; try{profiles=JSON.parse(fs.readFileSync(profilePath,'utf8'))}catch{}
const saveProfiles=()=>fs.writeFileSync(profilePath,JSON.stringify(profiles,null,2));
app.get('/api/cards',(q,r)=>r.json(cards)); app.get('/api/profile/:id',(q,r)=>r.json(profiles[q.params.id]||null));
app.post('/api/profile',(q,r)=>{const {playerId,name,deck}=q.body||{}; if(!playerId||!name||!Array.isArray(deck))return r.status(400).json({error:'invalid'}); if(deck.some(id=>!byId[id]||byId[id].isUnobtainable))return r.status(400).json({error:'invalid card'}); profiles[playerId]={name:String(name).slice(0,20),deck:deck.slice(0,20)}; saveProfiles();r.json(profiles[playerId]);});
let queue=[],games=new Map(); const roomOf=s=>[...games].find(([,g])=>g.players.some(p=>p.socketId===s.id));
const cloneCard=id=>{const c=byId[id];return c&&{uid:Math.random().toString(36).slice(2),id,hp:c.hp||0,maxHp:c.hp||0,status:[],items:[]}};
function player(socketId,profile){let deck=[...profile.deck].sort(()=>Math.random()-.5);return{socketId,name:profile.name,deck,hand:deck.splice(0,5),field:[],discard:[]}}
function view(g){return{id:g.id,turn:g.turn,ended:g.ended,winner:g.winner,players:g.players.map(p=>({name:p.name,deckCount:p.deck.length,hand:p.hand,field:p.field,discard:p.discard}))}}
function emit(g,event){io.to(g.id).emit('state',view(g)); if(event)io.to(g.id).emit('effect',event)}
function tick(g,p){for(const m of p.field){for(const i of m.items){const sk=byId[i]?.skills?.[0];if(sk?.type==='passive_heal')m.hp=Math.min(m.maxHp,m.hp+sk.turnHeal)} m.status=m.status.map(s=>({...s,duration:s.duration-1})).filter(s=>s.duration>0)} }
function damage(m,n){let red=0;for(const s of m.status)if(s.type==='shield')red=Math.max(red,s.value);for(const i of m.items){const sk=byId[i]?.skills?.[0];if(sk?.type==='passive_reduction')n-=sk.damageReduction}n=Math.max(0,Math.round(n*(1-red/100)));if(m.status.some(s=>s.type==='survive'))m.hp=Math.max(1,m.hp-n);else m.hp=Math.max(0,m.hp-n);return n}
function cleanup(g){for(const p of g.players){p.field=p.field.filter(m=>{if(m.hp>0)return true;p.discard.push(m.id);return false})}for(const p of g.players)if(!p.field.length&&!p.hand.some(id=>(byId[id]?.hp||0)>0)&&!p.deck.some(id=>(byId[id]?.hp||0)>0)){g.ended=true;g.winner=g.players.find(x=>x!==p)?.name}}
function target(g,pi,uid){for(const p of g.players)for(const m of p.field)if(m.uid===uid)return{p,m,enemy:p!==g.players[pi]};return null}
io.on('connection',s=>{
 s.on('matchmake',playerId=>{const prof=profiles[playerId];if(!prof)return s.emit('errorMsg','프로필/덱을 먼저 저장하세요.');queue=queue.filter(x=>x.id!==s.id);queue.push({id:s.id,prof});if(queue.length>=2){const a=queue.shift(),b=queue.shift(),id='g_'+Date.now(),g={id,players:[player(a.id,a.prof),player(b.id,b.prof)],turn:0,ended:false,winner:null};games.set(id,g);io.sockets.sockets.get(a.id)?.join(id);io.sockets.sockets.get(b.id)?.join(id);emit(g,{type:'match',text:'매치 성사!'});}else s.emit('queue','상대를 찾는 중');});
 s.on('action',a=>{const hit=roomOf(s);if(!hit)return;const [,g]=hit,pi=g.players.findIndex(p=>p.socketId===s.id),me=g.players[pi],op=g.players[1-pi];if(g.ended||g.turn!==pi)return s.emit('errorMsg','현재 행동할 수 없습니다.');let ev={type:a.type};
  if(a.type==='play'){const k=me.hand.indexOf(a.cardId),c=byId[a.cardId];if(k<0||!c)return;if(c.hp){if(c.evolvesFrom){const base=me.field.findIndex(x=>x.id===c.evolvesFrom);if(base<0)return s.emit('errorMsg','진화 전 카드가 필드에 필요합니다.');const evolved=cloneCard(c.id);evolved.hp=Math.min(evolved.maxHp,Math.max(1,me.field[base].hp+(evolved.maxHp-me.field[base].maxHp)));evolved.items=me.field[base].items;me.field[base]=evolved;}else{if(me.field.length>=3)return s.emit('errorMsg','필드는 최대 3장입니다.');me.field.push(cloneCard(c.id));}me.hand.splice(k,1);ev={type:'summon',text:`${me.name}: ${c.name} 소환`};}else{const t=target(g,pi,a.targetUid);if(!t)return;sApply(g,pi,c.skills[0],t.m);me.hand.splice(k,1);me.discard.push(c.id);ev={type:'item',text:`${me.name}: ${c.name} 사용`};}}
  else if(a.type==='skill'){const src=me.field.find(x=>x.uid===a.sourceUid),c=src&&byId[src.id],sk=c?.skills?.[a.skillIndex];if(!sk)return;const disabled=src.status.find(x=>x.type==='sleep'||x.type==='paralysis');if(disabled){src.status=src.status.filter(x=>x!==disabled);ev={type:'status',text:`${c.name}은(는) 행동 불가`};}else{let forced=op.field.find(x=>x.status.some(z=>z.type==='redirect'));let confused=src.status.some(x=>x.type==='confusion');let chosen=confused?[...me.field,...op.field][Math.floor(Math.random()*(me.field.length+op.field.length))]:forced||target(g,pi,a.targetUid)?.m;let targets=sk.type==='multi'?op.field:[chosen].filter(Boolean);if(sk.type==='heal'||sk.type==='shield')targets=[target(g,pi,a.targetUid)?.m||src];for(const m of targets)sApply(g,pi,sk,m,src);ev={type:sk.element||sk.type,text:`${me.name}: ${sk.name}`};}}
  else return;cleanup(g);if(!g.ended){g.turn=1-g.turn;tick(g,g.players[g.turn]);if(g.players[g.turn].deck.length&&g.players[g.turn].hand.length<7)g.players[g.turn].hand.push(g.players[g.turn].deck.shift())}emit(g,ev);
 });
 s.on('disconnect',()=>{queue=queue.filter(x=>x.id!==s.id);const h=roomOf(s);if(h){const[,g]=h;g.ended=true;g.winner=g.players.find(p=>p.socketId!==s.id)?.name;emit(g,{type:'leave',text:'상대 연결 종료'});}})
});
function sApply(g,pi,sk,m,src){if(!sk||!m)return;let amount=sk.damage||0;if(src){for(const id of src.items){const x=byId[id]?.skills?.[0];if(x?.type==='buff')amount+=x.attackBonus}const pass=byId[src.id]?.passive;if(pass?.type==='equipment_damage_bonus')amount+=src.items.length*pass.amountPerItem}
 if(amount)damage(m,amount);if(sk.heal)m.hp=Math.min(m.maxHp,m.hp+sk.heal);if(sk.type==='shield')m.status.push({type:'shield',value:sk.shieldPercent,duration:sk.duration});if(sk.statusType)m.status.push({type:sk.statusType,duration:sk.duration});if(sk.type==='passive_reduction'||sk.type==='buff'||sk.type==='passive_heal'){m.items.push(Object.keys(byId).find(id=>byId[id].skills?.[0]===sk))}if(sk.type==='survive_at_one')m.status.push({type:'survive',duration:sk.duration});if(sk.type==='cleanse_all')for(const x of g.players[pi].field)x.status=[];if(sk.type==='draw_random')for(let i=0;i<sk.count&&g.players[pi].deck.length;i++)g.players[pi].hand.push(g.players[pi].deck.shift());if(sk.type==='draw_monster'){const p=g.players[pi],idx=p.deck.findIndex(id=>byId[id]?.hp);if(idx>=0)p.hand.push(p.deck.splice(idx,1)[0])}if(sk.type==='confuse_all')for(const x of g.players[1-pi].field)x.status.push({type:'confusion',duration:sk.duration});if(sk.type==='coin_heal_or_damage')Math.random()<.5?m.hp=Math.min(m.maxHp,m.hp+sk.amount):damage(m,sk.amount);if(sk.type==='return_opponent_hand'){const p=g.players[1-pi];p.deck.push(...p.hand);p.hand=[];p.deck.sort(()=>Math.random()-.5)}if(sk.type==='redirect_attack')m.status.push({type:'redirect',duration:sk.duration});}
server.listen(process.env.PORT||3000,()=>console.log('http://localhost:'+(process.env.PORT||3000)));
