const express=require('express'),http=require('http'),fs=require('fs'),path=require('path');
const {Server}=require('socket.io');
const app=express(),server=http.createServer(app),io=new Server(server),ROOT=__dirname;
app.use(express.json());app.use(express.static(path.join(ROOT,'public')));app.use('/image',express.static(path.join(ROOT,'image')));
const cards=JSON.parse(fs.readFileSync(path.join(ROOT,'cards.json'),'utf8')),byId=Object.fromEntries(cards.map(c=>[c.id,c]));
const dataDir=process.env.DATA_DIR||ROOT;fs.mkdirSync(dataDir,{recursive:true});const profilePath=path.join(dataDir,'profiles.json');
let profiles={};try{profiles=JSON.parse(fs.readFileSync(profilePath,'utf8'))}catch{}const persist=()=>fs.writeFileSync(profilePath,JSON.stringify(profiles,null,2));
app.get('/healthz',(_,r)=>r.send('ok'));app.get('/api/cards',(_,r)=>r.json(cards));app.get('/api/profile/:id',(q,r)=>r.json(profiles[q.params.id]||null));
app.post('/api/profile',(q,r)=>{const {playerId,name,deck}=q.body||{};const count={};if(!playerId||!String(name||'').trim()||!Array.isArray(deck)||deck.length>20||deck.some(id=>!byId[id]||byId[id].isUnobtainable||((count[id]=(count[id]||0)+1)>2)))return r.status(400).json({error:'덱은 최대 20장, 같은 카드는 최대 2장입니다.'});profiles[playerId]={name:String(name).trim().slice(0,20),deck};persist();r.json(profiles[playerId])});
let queue=[],games=new Map();const uid=()=>Math.random().toString(36).slice(2);const unit=id=>({uid:uid(),id,hp:byId[id].hp,maxHp:byId[id].hp,status:[],items:[]});
function makePlayer(socketId,playerId,p){const deck=[...p.deck].sort(()=>Math.random()-.5);return{socketId,playerId,name:p.name,deck,hand:deck.splice(0,5),field:[],discard:[]}}
function publicPlayer(p,self){return{name:p.name,deckCount:p.deck.length,hand:self?p.hand:[],handCount:p.hand.length,field:p.field,discardCount:p.discard.length}}
function send(g,e){g.players.forEach((p,i)=>io.to(p.socketId).emit('state',{id:g.id,you:i,turn:g.turn,ended:g.ended,winner:g.winner,players:g.players.map((x,j)=>publicPlayer(x,i===j))}));if(e)io.to(g.id).emit('effect',e)}
const room=s=>[...games.values()].find(g=>g.players.some(p=>p.socketId===s.id));
function damage(m,n){let pct=Math.max(0,...m.status.filter(x=>x.type==='shield').map(x=>x.value));for(const id of m.items){const sk=byId[id]?.skills?.[0];if(sk?.type==='passive_reduction')n-=sk.damageReduction}n=Math.max(0,Math.round(n*(1-pct/100)));m.hp=m.status.some(x=>x.type==='survive')?Math.max(1,m.hp-n):Math.max(0,m.hp-n)}
function apply(g,pi,sk,m,src,itemId){if(!sk)return;let n=sk.damage||0;if(src){for(const id of src.items){const x=byId[id]?.skills?.[0];if(x?.type==='buff')n+=x.attackBonus}const p=byId[src.id]?.passive;if(p?.type==='equipment_damage_bonus')n+=src.items.length*p.amountPerItem}if(m&&n)damage(m,n);if(m&&sk.heal)m.hp=Math.min(m.maxHp,m.hp+sk.heal);if(m&&sk.type==='shield')m.status.push({type:'shield',value:sk.shieldPercent,duration:sk.duration});if(m&&sk.statusType)m.status.push({type:sk.statusType,duration:sk.duration});if(m&&['passive_reduction','buff','passive_heal'].includes(sk.type))m.items.push(itemId);if(m&&sk.type==='survive_at_one')m.status.push({type:'survive',duration:sk.duration});const me=g.players[pi],op=g.players[1-pi];if(sk.type==='cleanse_all')me.field.forEach(x=>x.status=[]);if(sk.type==='draw_random')for(let i=0;i<sk.count&&me.deck.length&&me.hand.length<7;i++)me.hand.push(me.deck.shift());if(sk.type==='draw_monster'){const i=me.deck.findIndex(id=>byId[id]?.hp);if(i>=0&&me.hand.length<7)me.hand.push(me.deck.splice(i,1)[0])}if(sk.type==='confuse_all')op.field.forEach(x=>x.status.push({type:'confusion',duration:sk.duration}));if(m&&sk.type==='coin_heal_or_damage')Math.random()<.5?m.hp=Math.min(m.maxHp,m.hp+sk.amount):damage(m,sk.amount);if(sk.type==='return_opponent_hand'){op.deck.push(...op.hand);op.hand=[];op.deck.sort(()=>Math.random()-.5)}if(m&&sk.type==='redirect_attack')m.status.push({type:'redirect',duration:sk.duration})}
function endTurn(g){for(const p of g.players){p.field=p.field.filter(m=>{if(m.hp>0)return true;p.discard.push(m.id);return false})}for(const p of g.players)if(!p.field.length&&!p.hand.some(id=>byId[id]?.hp)&&!p.deck.some(id=>byId[id]?.hp)){g.ended=true;g.winner=g.players.find(x=>x!==p)?.name}if(g.ended)return;g.turn=1-g.turn;const p=g.players[g.turn];p.field.forEach(m=>{m.items.forEach(id=>{const sk=byId[id]?.skills?.[0];if(sk?.type==='passive_heal')m.hp=Math.min(m.maxHp,m.hp+sk.turnHeal)});m.status=m.status.map(x=>({...x,duration:x.duration-1})).filter(x=>x.duration>0)});if(p.deck.length&&p.hand.length<7)p.hand.push(p.deck.shift())}
io.on('connection',s=>{s.on('matchmake',playerId=>{const p=profiles[playerId];if(!p||!p.deck.length)return s.emit('errorMsg','닉네임과 1장 이상의 덱을 먼저 저장하세요.');queue=queue.filter(x=>x.socketId!==s.id);queue.push({socketId:s.id,playerId,p});s.emit('queue','상대를 찾는 중...');if(queue.length>1){const a=queue.shift(),b=queue.shift(),g={id:'game_'+Date.now(),players:[makePlayer(a.socketId,a.playerId,a.p),makePlayer(b.socketId,b.playerId,b.p)],turn:0,ended:false,winner:null};games.set(g.id,g);g.players.forEach(x=>io.sockets.sockets.get(x.socketId)?.join(g.id));send(g,{type:'match',text:'매치 성사!'})}});
s.on('action',a=>{const g=room(s);if(!g)return;const pi=g.players.findIndex(p=>p.socketId===s.id),me=g.players[pi],op=g.players[1-pi];if(g.ended||g.turn!==pi)return s.emit('errorMsg','현재 내 턴이 아닙니다.');let text='';if(a.type==='play'){const i=me.hand.indexOf(a.cardId),c=byId[a.cardId];if(i<0||!c)return;if(c.hp){if(c.evolvesFrom){const j=me.field.findIndex(x=>x.id===c.evolvesFrom);if(j<0)return s.emit('errorMsg','진화 전 카드가 필드에 필요합니다.');const u=unit(c.id);u.hp=Math.min(u.maxHp,me.field[j].hp+u.maxHp-me.field[j].maxHp);u.items=me.field[j].items;me.field[j]=u}else{if(me.field.length>=3)return s.emit('errorMsg','필드는 최대 3장입니다.');me.field.push(unit(c.id))}}else{const m=[...me.field,...op.field].find(x=>x.uid===a.targetUid);const noTarget=['draw_monster','draw_random','confuse_all','cleanse_all','return_opponent_hand'].includes(c.skills?.[0]?.type);if(!m&&!noTarget)return s.emit('errorMsg','대상을 선택하세요.');apply(g,pi,c.skills[0],m,null,c.id)}me.hand.splice(i,1);if(!c.hp)me.discard.push(c.id);text=`${me.name}: ${c.name} 사용`}else if(a.type==='skill'){const src=me.field.find(x=>x.uid===a.sourceUid),sk=src&&byId[src.id]?.skills?.[a.skillIndex];if(!src||!sk)return;const stop=src.status.find(x=>['sleep','paralysis'].includes(x.type));if(stop){src.status=src.status.filter(x=>x!==stop);text=`${byId[src.id].name}: 상태이상으로 행동 불가`}else{let chosen=[...me.field,...op.field].find(x=>x.uid===a.targetUid);const forced=op.field.find(x=>x.status.some(z=>z.type==='redirect'));if(forced&&sk.type==='single')chosen=forced;if(src.status.some(x=>x.type==='confusion')){const all=[...me.field,...op.field];chosen=all[Math.floor(Math.random()*all.length)]}const targets=sk.type==='multi'?op.field:[chosen||((sk.type==='heal'||sk.type==='shield')?src:null)].filter(Boolean);if(!targets.length)return s.emit('errorMsg','대상을 선택하세요.');targets.forEach(m=>apply(g,pi,sk,m,src));text=`${me.name}: ${sk.name}`}}else return;endTurn(g);send(g,{type:'action',text})});
s.on('disconnect',()=>{queue=queue.filter(x=>x.socketId!==s.id);const g=room(s);if(g&&!g.ended){g.ended=true;g.winner=g.players.find(x=>x.socketId!==s.id)?.name;send(g,{type:'leave',text:'상대 연결 종료'})}})});
server.listen(process.env.PORT||3000,()=>console.log(`GOA Card Game: ${process.env.PORT||3000}`));
