const express=require('express'),http=require('http'),fs=require('fs'),path=require('path');
const app=express(),server=http.createServer(app),{Server}=require('socket.io'),io=new Server(server),ROOT=__dirname;
app.use(express.json());app.use(express.static(path.join(ROOT,'public')));app.use('/image',express.static(path.join(ROOT,'image')));
const cards=JSON.parse(fs.readFileSync(path.join(ROOT,'cards.json'),'utf8')),byId=Object.fromEntries(cards.map(c=>[c.id,c]));
const dir=process.env.DATA_DIR||ROOT;fs.mkdirSync(dir,{recursive:true});const db=path.join(dir,'profiles.json');let profiles={};try{profiles=JSON.parse(fs.readFileSync(db,'utf8'))}catch{};
const save=()=>fs.writeFileSync(db,JSON.stringify(profiles,null,2));app.get('/healthz',(_,r)=>r.send('ok'));app.get('/api/cards',(_,r)=>r.json(cards));app.get('/api/profile/:id',(q,r)=>r.json(profiles[q.params.id]||null));
app.post('/api/profile',(q,r)=>{let {playerId,name,deck}=q.body||{},n={};if(!playerId||!String(name||'').trim()||!Array.isArray(deck)||deck.length>20||deck.some(id=>!byId[id]||byId[id].isUnobtainable||((n[id]=(n[id]||0)+1)>2)))return r.status(400).json({error:'닉네임, 덱 제한을 확인하세요.'});profiles[playerId]={name:String(name).trim().slice(0,20),deck};save();r.json(profiles[playerId])});
let queue=[],games=new Map();const uid=()=>Math.random().toString(36).slice(2),unit=id=>({uid:uid(),id,hp:byId[id].hp,maxHp:byId[id].hp,status:[]});
function mk(s,id,p){let deck=[...p.deck].sort(()=>Math.random()-.5);return{socketId:s,playerId:id,name:p.name,deck,hand:deck.splice(0,5),field:[],discard:[]}}
function emit(g,e){g.players.forEach((p,i)=>io.to(p.socketId).emit('state',{you:i,turn:g.turn,ended:g.ended,winner:g.winner,players:g.players.map((x,j)=>({name:x.name,deckCount:x.deck.length,hand:i===j?x.hand:[],handCount:x.hand.length,field:x.field}))}));if(e)io.to(g.id).emit('effect',e)}
const findGame=s=>[...games.values()].find(g=>g.players.some(p=>p.socketId===s.id));
function hit(m,n){let pct=Math.max(0,...m.status.filter(x=>x.type==='shield').map(x=>x.value));m.hp=Math.max(m.status.some(x=>x.type==='survive')?1:0,m.hp-Math.max(0,Math.round(n*(1-pct/100))))}
function apply(g,pi,sk,m){if(!sk)return;const me=g.players[pi],op=g.players[1-pi];if(m&&sk.damage)hit(m,sk.damage);if(m&&sk.heal)m.hp=Math.min(m.maxHp,m.hp+sk.heal);if(m&&sk.type==='shield')m.status.push({type:'shield',value:sk.shieldPercent,duration:sk.duration});if(m&&sk.statusType)m.status.push({type:sk.statusType,duration:sk.duration});if(m&&sk.type==='survive_at_one')m.status.push({type:'survive',duration:sk.duration});if(sk.type==='cleanse_all')me.field.forEach(x=>x.status=[]);if(sk.type==='draw_random')for(let i=0;i<sk.count&&me.deck.length&&me.hand.length<7;i++)me.hand.push(me.deck.shift());if(sk.type==='draw_monster'){let i=me.deck.findIndex(id=>byId[id]?.hp);if(i>=0&&me.hand.length<7)me.hand.push(me.deck.splice(i,1)[0])}if(sk.type==='confuse_all')op.field.forEach(x=>x.status.push({type:'confusion',duration:sk.duration}));if(m&&sk.type==='coin_heal_or_damage')Math.random()<.5?m.hp=Math.min(m.maxHp,m.hp+sk.amount):hit(m,sk.amount);if(sk.type==='return_opponent_hand'){op.deck.push(...op.hand);op.hand=[];op.deck.sort(()=>Math.random()-.5)}}
function finish(g){g.players.forEach(p=>p.field=p.field.filter(m=>m.hp>0));for(const p of g.players)if(!p.field.length&&!p.hand.some(id=>byId[id]?.hp)&&!p.deck.some(id=>byId[id]?.hp)){g.ended=true;g.winner=g.players.find(x=>x!==p)?.name}if(g.ended)return;g.turn=1-g.turn;let p=g.players[g.turn];p.field.forEach(m=>m.status=m.status.map(x=>({...x,duration:x.duration-1})).filter(x=>x.duration>0));if(p.deck.length&&p.hand.length<7)p.hand.push(p.deck.shift())}
io.on('connection',s=>{s.on('matchmake',id=>{let p=profiles[id];if(!p||!p.deck.length)return s.emit('errorMsg','닉네임과 덱을 먼저 설정하세요.');queue=queue.filter(x=>x.s!==s.id);queue.push({s:s.id,id,p});s.emit('queue','상대를 찾는 중...');if(queue.length>=2){let a=queue.shift(),b=queue.shift(),g={id:'g'+Date.now(),players:[mk(a.s,a.id,a.p),mk(b.s,b.id,b.p)],turn:0,ended:false};games.set(g.id,g);g.players.forEach(x=>io.sockets.sockets.get(x.socketId)?.join(g.id));emit(g,{text:'매치 성사!'})}});
s.on('action',a=>{let g=findGame(s);if(!g)return;let pi=g.players.findIndex(p=>p.socketId===s.id),me=g.players[pi],op=g.players[1-pi];if(g.ended||g.turn!==pi)return s.emit('errorMsg','내 턴이 아닙니다.');let text='';if(a.type==='play'){let i=me.hand.indexOf(a.cardId),c=byId[a.cardId];if(i<0||!c)return;if(c.hp){if(me.field.length>=3)return s.emit('errorMsg','필드는 최대 3장입니다.');me.field.push(unit(c.id))}else{let m=[...me.field,...op.field].find(x=>x.uid===a.targetUid),free=['draw_monster','draw_random','confuse_all','cleanse_all','return_opponent_hand'].includes(c.skills?.[0]?.type);if(!m&&!free)return s.emit('errorMsg','대상을 선택하세요.');apply(g,pi,c.skills[0],m)}me.hand.splice(i,1);text=`${me.name}: ${c.name} 사용`}else if(a.type==='skill'){let src=me.field.find(x=>x.uid===a.sourceUid),sk=src&&byId[src.id]?.skills?.[a.skillIndex];if(!src||!sk)return;let stop=src.status.find(x=>['sleep','paralysis'].includes(x.type));if(stop){src.status=src.status.filter(x=>x!==stop);text='상태이상으로 행동 불가'}else{let m=[...me.field,...op.field].find(x=>x.uid===a.targetUid),targets=sk.type==='multi'?op.field:[m||(['heal','shield'].includes(sk.type)?src:null)].filter(Boolean);if(!targets.length)return s.emit('errorMsg','대상을 선택하세요.');targets.forEach(x=>apply(g,pi,sk,x));text=`${me.name}: ${sk.name}`}}finish(g);emit(g,{text})});s.on('disconnect',()=>{queue=queue.filter(x=>x.s!==s.id);let g=findGame(s);if(g&&!g.ended){g.ended=true;g.winner=g.players.find(x=>x.socketId!==s.id)?.name;emit(g,{text:'상대 연결 종료'})}})});
server.listen(process.env.PORT||3000);
