const express=require('express'),http=require('http'),fs=require('fs'),path=require('path');
const app=express(),server=http.createServer(app),{Server}=require('socket.io'),io=new Server(server,{pingTimeout:20000});
const ROOT=__dirname,cards=JSON.parse(fs.readFileSync(path.join(ROOT,'cards.json'),'utf8')),byId=Object.fromEntries(cards.map(c=>[c.id,c]));
app.use(express.json());app.use(express.static(path.join(ROOT,'public')));app.use('/image',express.static(path.join(ROOT,'image')));
const dir=process.env.DATA_DIR||ROOT,db=path.join(dir,'profiles.json');fs.mkdirSync(dir,{recursive:true});let profiles={};try{profiles=JSON.parse(fs.readFileSync(db,'utf8'))}catch{}const persist=()=>fs.writeFileSync(db,JSON.stringify(profiles,null,2));
const allowed=id=>byId[id]&&!byId[id].isUnobtainable&&id!=='dummy_card';const valid=d=>{const n={};return Array.isArray(d)&&d.length<=20&&d.every(id=>allowed(id)&&((n[id]=(n[id]||0)+1)<=2))};
app.get('/healthz',(_,r)=>r.send('ok'));app.get('/api/cards',(_,r)=>r.json(cards));app.get('/api/profile/:id',(q,r)=>r.json(profiles[q.params.id]||null));app.post('/api/profile',(q,r)=>{const{playerId,name,deck}=q.body||{};if(!playerId||!String(name||'').trim()||!valid(deck))return r.status(400).json({error:'프로필 오류'});profiles[playerId]={name:String(name).trim().slice(0,20),deck:[...deck]};persist();r.json(profiles[playerId])});
let queue=[],games=new Map(),seq=0;const unit=id=>({uid:`u${Date.now()}_${++seq}`,id,hp:byId[id].hp,maxHp:byId[id].hp,status:[]});
function player(socketId,id,p){const deck=[...p.deck].sort(()=>Math.random()-.5);return{socketId,id,name:p.name,deck,hand:deck.splice(0,Math.min(5,deck.length)),active:null,bench:[],trash:[],bot:false}}
const bot=()=>({socketId:null,id:'BOT',name:'허수아비 봇',deck:[],hand:[],active:unit('dummy_card'),bench:[unit('dummy_card'),unit('dummy_card')],trash:[],bot:true});
function publicP(p,self){return{name:p.name,deckCount:p.deck.length,hand:self?p.hand:[],handCount:p.hand.length,active:p.active,bench:p.bench,trash:p.trash}}
function state(g,you){return{you,turn:g.turn,ended:g.ended,winner:g.winner||null,botGame:g.botGame,players:g.players.map((p,i)=>publicP(p,i===you))}}
function send(g,e){g.players.filter(p=>p.socketId).forEach(p=>io.to(p.socketId).emit('game:state',state(g,g.players.indexOf(p))));if(e)g.players.filter(p=>p.socketId).forEach(p=>io.to(p.socketId).emit('game:effect',e))}
const gameOf=id=>[...games.values()].find(g=>g.players.some(p=>p.socketId===id));
function makeGame(a,b,botGame=false){const g={id:`g${Date.now()}_${++seq}`,players:[a,b],turn:0,ended:false,botGame};games.set(g.id,g);[a,b].filter(p=>p.socketId).forEach(p=>io.sockets.sockets.get(p.socketId)?.join(g.id));send(g,{text:botGame?'허수아비 봇전 시작!':'매치 성사!'})}
function doMatch(){queue=queue.filter(x=>io.sockets.sockets.has(x.sid));while(queue.length>1){const a=queue.shift(),b=queue.shift();makeGame(player(a.sid,a.id,a.p),player(b.sid,b.id,b.p))}}
function allUnits(p){return [p.active,...p.bench].filter(Boolean)}function findUnit(g,uid){for(const p of g.players)for(const u of allUnits(p))if(u.uid===uid)return u}
function damage(m,n){const shield=Math.max(0,...m.status.filter(s=>s.type==='shield').map(s=>s.value));m.hp=Math.max(0,m.hp-Math.round(n*(1-shield/100)))}
function apply(g,pi,sk,target){const me=g.players[pi],op=g.players[1-pi];if(target&&sk.damage)damage(target,sk.damage);if(target&&sk.heal)target.hp=Math.min(target.maxHp,target.hp+sk.heal);if(target&&sk.type==='shield')target.status.push({type:'shield',value:sk.shieldPercent,duration:sk.duration||1});if(target&&sk.statusType)target.status.push({type:sk.statusType,duration:sk.duration||1});if(sk.type==='cleanse_all')allUnits(me).forEach(u=>u.status=[]);if(sk.type==='draw_random')for(let i=0;i<sk.count&&me.deck.length&&me.hand.length<7;i++)me.hand.push(me.deck.shift());if(sk.type==='draw_monster'){const i=me.deck.findIndex(id=>byId[id]?.hp);if(i>=0&&me.hand.length<7)me.hand.push(me.deck.splice(i,1)[0])}if(sk.type==='confuse_all')allUnits(op).forEach(u=>u.status.push({type:'confusion',duration:sk.duration||1}));if(target&&sk.type==='coin_heal_or_damage')Math.random()<.5?target.hp=Math.min(target.maxHp,target.hp+sk.amount):damage(target,sk.amount);if(sk.type==='return_opponent_hand'){op.deck.push(...op.hand);op.hand=[];op.deck.sort(()=>Math.random()-.5)}}
function clean(p){if(p.active&&p.active.hp<=0){p.trash.push(p.active.id);p.active=p.bench.shift()||null}p.bench=p.bench.filter(u=>{if(u.hp>0)return true;p.trash.push(u.id);return false})}function defeated(p){return !p.active&&!p.bench.length&&!p.hand.some(id=>byId[id]?.hp)&&!p.deck.some(id=>byId[id]?.hp)}
function advance(g){g.players.forEach(clean);for(let i=0;i<2;i++)if(defeated(g.players[i])){g.ended=true;g.winner=g.players[1-i].name;return}g.turn=1-g.turn;const p=g.players[g.turn];allUnits(p).forEach(u=>u.status=u.status.map(s=>({...s,duration:s.duration-1})).filter(s=>s.duration>0));if(p.deck.length&&p.hand.length<7)p.hand.push(p.deck.shift())}
function botTurn(g){if(g.ended||!g.players[g.turn].bot)return;setTimeout(()=>{const b=g.players[1],h=g.players[0];if(b.active&&h.active){const sk=byId.dummy_card.skills[0];apply(g,1,sk,h.active);advance(g);send(g,{text:`허수아비 봇: ${sk.name}`})}else{advance(g);send(g,{text:'봇이 턴을 넘겼습니다.'})}},550)}
io.on('connection',s=>{s.emit('server:ready');s.on('match:join',id=>{const p=profiles[id];if(!p||!p.deck.length)return s.emit('app:error','닉네임과 덱을 먼저 설정하세요.');queue=queue.filter(x=>x.sid!==s.id&&x.id!==id);queue.push({sid:s.id,id,p});s.emit('match:waiting','상대를 찾는 중...');doMatch()});s.on('match:cancel',()=>{queue=queue.filter(x=>x.sid!==s.id);s.emit('match:cancelled')});s.on('bot:start',id=>{const p=profiles[id];if(!p||!p.deck.length)return s.emit('app:error','닉네임과 덱을 먼저 설정하세요.');queue=queue.filter(x=>x.sid!==s.id);makeGame(player(s.id,id,p),bot(),true)});
s.on('game:action',a=>{const g=gameOf(s.id);if(!g||g.ended)return;const pi=g.players.findIndex(p=>p.socketId===s.id);if(g.turn!==pi)return s.emit('app:error','내 턴이 아닙니다.');const me=g.players[pi],op=g.players[1-pi];let text='';if(a.type==='play'){const i=me.hand.indexOf(a.cardId),c=byId[a.cardId];if(i<0||!c)return;if(c.hp){const u=unit(c.id);if(!me.active)me.active=u;else if(me.bench.length<3)me.bench.push(u);else return s.emit('app:error','벤치는 최대 3장입니다.')}else{const sk=c.skills?.[0],target=findUnit(g,a.targetUid);const free=['draw_monster','draw_random','confuse_all','cleanse_all','return_opponent_hand'].includes(sk?.type);if(!target&&!free)return s.emit('app:error','대상을 먼저 선택하세요.');apply(g,pi,sk,target);me.trash.push(c.id)}me.hand.splice(i,1);text=`${me.name}: ${c.name} 사용`}else if(a.type==='skill'){if(!me.active||me.active.uid!==a.sourceUid)return s.emit('app:error','배틀 필드 카드만 공격할 수 있습니다.');const sk=byId[me.active.id]?.skills?.[a.skillIndex];if(!sk)return;let targets=sk.type==='multi'?allUnits(op):[findUnit(g,a.targetUid)||(['heal','shield'].includes(sk.type)?me.active:null)].filter(Boolean);if(!targets.length)return s.emit('app:error','대상을 먼저 선택하세요.');targets.forEach(t=>apply(g,pi,sk,t));text=`${me.name}: ${sk.name}`}else if(a.type==='switch'){const i=me.bench.findIndex(u=>u.uid===a.uid);if(i<0||!me.active)return;[me.active,me.bench[i]]=[me.bench[i],me.active];text=`${me.name}: 배틀 카드 교체`}else return;advance(g);send(g,{text});botTurn(g)});s.on('disconnect',()=>{queue=queue.filter(x=>x.sid!==s.id);const g=gameOf(s.id);if(g&&!g.ended&&!g.botGame){g.ended=true;g.winner=g.players.find(p=>p.socketId!==s.id)?.name;send(g,{text:'상대 연결 종료'})}})});
server.listen(process.env.PORT||3000,()=>console.log('GOA Card Game ready'));
